### ISSUE TITLE
Height of horizontal separator is wrong

### ISSUE THREAD

**Issue by tom-englert** [iSerganov/ninja-splitter#1]
**Describe the bug**
Horizontal separator does not follow the thickness, it's always 1px

**To Reproduce**
Root cause is a typo in `height`:
https://github.com/iSerganov/ninja-splitter/blob/4abc8017fa20ae8f5a45f9569165589aba277029/projects/ninja-split/src/lib/ninja-separator.component.ts#L27

**Comment by iSerganov** [comment]
@tom-englert, thank you for this catch!
I will have a look and fix asap.

**Comment by iSerganov** [comment]
Fixed in v.1.1.13

**Comment by tom-englert** [comment]
👍 😄
